Agent consistently sleeps after receiving commands
mitre/gocat pull request #46
Opened 2021-02-09 02:40 UTC by unkempthenry

Rework core.go so that we still sleep after receiving and dispatching instructions. Reduces extraneous c2 traffic.

Background: 

The branch in `runAgent` that executes when an agent receives instructions does not sleep before reissuing another beacon (there is a call to sleep here, but in this case this is to the "jitter" value which defaults to 0 and is separate from the agent sleep window).  

This was difficult to notice happening since we hide instructions from agents once they're collected -- however, if we adopt https://github.com/mitre/caldera/pull/2021 (IMO a good change), then sandcat as-is will continually execute the same instruction until a result is returned to the server and saved. 

Note a valuable followup would be to move the instruction results into the same beacon instead of firing on demand requests to further reduce c2 traffic (this, I think, would align more closely to the expectations users have when configuring the sleep interval for agents).

2021-02-23 18:50 UTC, supersquirel500 approved these changes
Accomplishes my previous pull request but with better implementation.

2021-03-12 17:29 UTC, wbooth requested changes
Pending testing outcome

2021-03-16 15:37 UTC, mrengstrom commented on core/core.go
> +}
Were the whitespace changes here and above done to align with the rest of the code?  It looks like so based on what I see.

2021-03-19 18:41 UTC, mrengstrom approved these changes

2021-03-22 02:57 UTC, merged